# =================================================================
# GENERAL PROJECT CONFIGURATION
# =================================================================
project_name: "critical_event_predictor"
random_seed: 42 



# =================================================================
# PARAMETERS FOR DATA PREPARATION (data_preparation.py)
# =================================================================
data_preparation:
  # Input and output paths
  input_dir: "data/raw"
  output_path: "data/processed/clean_data.csv"
  
  # Specific parameters for the cleaning process
  anomalous_value: -999999.0


# =================================================================
# PARAMETERS FOR DATA ANALYSIS (/notebooks/analysis/*/1_analysis.ipynb)
# =================================================================
1_analysis:
  paths:
    base_data_dir: '../../../data/'
    paros_pattern: 'raw/IPTO/Paros*.xlsx'
    syros_pattern: 'raw/IPTO/Syros*.xlsx'
    MesaDelSol_pattern: 'raw/MesaDelSol/*.csv'
    clean_data: 'clean/'


  # Excels parameters
  excel_settings:
    skip_rows: 5